import Head from 'next/head';
import Htag from "@/components/Htag/Htag";
import Button from "@/components/Button/Button";

// import { Htag, Button } from '../components'

export default function Home(): JSX.Element {
    return (
        <>
            <Head>
                <title>Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <h1>next</h1>
            <Htag tag={'h1'}>htag</Htag>
            <Button appearence={'primary'}>add</Button>
            <Button appearence={'ghost'}>add</Button>

        </>
    )
};
